### ISSUE TITLE
Issue with setting up user accounts - Google OAuth - Invalid Grant

### ISSUE THREAD

**Issue by Thunderbottom** [phasehq/console#232]
### Describe the bug

We've recently set up Phase alongside Google OAuth, but the initial login refuses to work. When I try to login, the app fails to redirect to the correct callback URL, causing "Secure Connection Failed". Here's the logs from the Frontend:

```js
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error invalid_grant (Bad Request) {
  error: OPError: invalid_grant (Bad Request)
      at processResponse (/app/node_modules/openid-client/lib/helpers/process_response.js:38:13)
      at Client.grant (/app/node_modules/openid-client/lib/client.js:1327:22)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Client.callback (/app/node_modules/openid-client/lib/client.js:476:24)
      at async oAuthCallback (/app/node_modules/next-auth/core/lib/oauth/callback.js:109:16)
      at async Object.callback (/app/node_modules/next-auth/core/routes/callback.js:52:11)
      at async AuthHandler (/app/node_modules/next-auth/core/index.js:208:28)
      at async NextAuthApiHandler (/app/node_modules/next-auth/next/index.js:22:19)
      at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)
      at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'google',
  message: 'invalid_grant (Bad Request)'
}
```

While I can also see in the backend logs, after enabling debug mode, that the user data comes through just fine from Google. There's something failing at the frontend since I can confirm that the configuration is correct.

Environment:

```env
NEXT_PUBLIC_BACKEND_API_BASE=https://phase.site.com/service
NEXTAUTH_URL=https://phase.site.com
NEXTAUTH_SECRET=areallylongsecret
NEXT_TELEMETRY_DISABLED=1
NEXT_PUBLIC_NEXTAUTH_PROVIDERS=google
OAUTH_REDIRECT_URI=https://phase.site.com
```

Do let me know if any more information is required.

### To Reproduce

1. Set up Phase with [Google OAuth](https://docs.phase.dev/self-hosting/configuration/envars#single-sign-on-ss-0)
2. Try to login
3. Check frontend logs.

### Expected behavior

The user is logged in.

**Comment by rohan-chaturvedi** [comment]
Hey @Thunderbottom , could you make sure that:
* `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET` are correctly set in your Environment? I didn't see it in the snippet you shared above
* The callback url is correctly set in the Google OAuth app? Given your example above, it should be `https://phase.site.com/api/auth/callback/google
`

**Comment by nimish-ks** [comment]
@rohan-chaturvedi - I think @Thunderbottom config is largely correct.

I suspect this issue has a something to with do how the frontend makes a request to the backend during outh over the local docker network.

@Thunderbottom Could you please the `BACKEND_API_BASE` variable to `${HTTP_PROTOCOL}${HOST}/service` so its the same as NEXT_PUBLIC_NEXTAUTH_PROVIDERS in your `docker-compose.yml` or your `.env`.

Following your example, it should be:
```env
BACKEND_API_BASE=https://phase.site.com/service
```

This will ensure the frontend is hitting the backend through the public API.

**Comment by Thunderbottom** [comment]
@rohan-chaturvedi I believe the OAuth details are set correctly, can confirm.

@nimish-ks I've added the variable to reflect the same as the `NEXT_PUBLIC_BACKEND_API_BASE`, but it still throws the same `Secure Connection Failed` error in the browser. If it helps, I'm using Firefox. Can try some other browser if required.

**Comment by Thunderbottom** [comment]
Quick update, works fine on Chrome, but not on Firefox, which is weird. Seems like it's got something to do with that. Would it be possible for you to check too somehow?

**Comment by rohan-chaturvedi** [comment]
> Quick update, works fine on Chrome, but not on Firefox, which is weird. Seems like it's got something to do with that. Would it be possible for you to check too somehow?

Yep, seems like I'm able to reproduce this behavior as well. Will investigate and get back to you with a fix asap!

**Comment by nimish-ks** [comment]
@Thunderbottom The inconsistency between browser is puzzling. We are not able to replicate with `BACKEND_API_BASE` set to a public host. eg. 
```env
BACKEND_API_BASE=https://phase.site.com/service
```

- Please make sure that the env is set correctly within the container by:
```fish
# List the containers
docker ps

# Shell into the container
docker exec -it 5daecb7e8386 /bin/sh

# Print the env
echo $BACKEND_API_BASE
```
- If you are using Cloudflare, try turning on 'Development Mode' to bypass any js cache.
- I've sent you an invite to our Slack. Would love to hop on a quick huddle figure this out.

**Comment by rohan-chaturvedi** [comment]
@Thunderbottom we've updated the `docker-compose.yml` with these fixes as well: https://github.com/phasehq/console/pull/234

**Comment by Thunderbottom** [comment]
Just got to this. I can confirm that the changes above do not fix the setup on Firefox. For more context, I have:

* set the `BACKEND_API_BASE` as the `/service` URL.
* moved the `OAUTH_REDIRECT_URI` to the backend container
* confirmed that there's no proxy (CF) in front of this

**Comment by nimish-ks** [comment]
update: this issue is caused when using HTTP/2 on AWS load balancer. you can temporarily resolve it by disable HTTP in the load balancer attributes.

![image (8)](https://github.com/phasehq/console/assets/85357445/c8ebfedf-7cef-4663-aebf-9a798633302f)

investigating this further.

**Comment by rohan-chaturvedi** [comment]
@Thunderbottom We've found the issue that caused this and raised a [PR](https://github.com/phasehq/console/pull/245) with a fix. Tl;dr is that NextAuth was adding ALL response headers received from the django backend back to the browser, causing Firefox to freak out. We've fixed it by manually adding only the required `set-cookie` header from django. 

You can test this fix by running `phasehq/frontend:246f132` from the PR build. We'll go ahead and merge this PR into a new release once you've had a chance to try it out.

**Comment by Thunderbottom** [comment]
Seems to be working fine now with the fix from #245, thanks!
