### ISSUE TITLE
Docker Compose: Login screen OAuth callback error with GitHub

### ISSUE THREAD

**Issue by FilipSwiatczak** [phasehq/console#270]
### Describe the bug

Frontend container throws Axios ECONNREFUSED on login with GitHub (out of the box config)
`AxiosError: connect ECONNREFUSED 127.0.0.1:443`
I'm a new user trying out the platform on local. 
I'm following the docker compose docs at https://docs.phase.dev/self-hosting/docker-compose.

Configured GitHub OAuth app with Authorization callback URL as https://localhost/api/auth/callback/github
Updated .env with auth keys, spun up with `docker-compose -f docker-compose.yml up -d`

Frontend container throws:
`AxiosError: connect ECONNREFUSED 127.0.0.1:443`
or
`AxiosError: connect ECONNREFUSED 127.0.0.1:80` if I change the protocol to http

### To Reproduce

1. Configure GitHub OAuth app with Auth callback URL as https://localhost/api/auth/callback/github
2. Spin up docker compose with `docker-compose -f docker-compose.yml up -d`
3. navigate to localhost
4. click on Login with Github
5. Loops back to login screen
6. Network tab logs: `https://localhost/api/auth/error?error=Callback` with 302 status
7. Network tab logs: `https://localhost/api/auth/signin?error=Callback` with 302 status
8. Network tab logs: `https://localhost/login?callbackUrl=https%3A%2F%2Flocalhost%2F&error=Callback`
200 status
9. phasehq/frontend:latest container throws: `AxiosError: connect ECONNREFUSED 127.0.0.1:443`

### Expected behavior
5.  Should take you to homepage

### Platform you are having the issue on:
docker-compose version 1.29.2, build 5becea4c
❯ docker version
Client:
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 OS/Arch:           darwin/arm64
Server: Docker Desktop 4.9.1 (81317)
 Engine:
  Version:          20.10.16

**Comment by rohan-chaturvedi** [comment]
Hey @FilipSwiatczak, would you mind sharing what `HTTP_PROTOCOL` and `HOST` values you have in your .env?

**Comment by FilipSwiatczak** [comment]
hey @rohan-chaturvedi , sure, it'a s standard out of the box setup, so:

```# Replace with your domain or host
HOST=localhost
HTTP_PROTOCOL=https://
```

I've re-run just to be sure and I got the error described (axios) and another one in the frontend container:
```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error State cookie was missing. {
  error: TypeError: State cookie was missing.
      at Object.use (/app/node_modules/next-auth/core/lib/oauth/checks.js:111:23)
      at oAuthCallback (/app/node_modules/next-auth/core/lib/oauth/callback.js:89:25)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.callback (/app/node_modules/next-auth/core/routes/callback.js:52:11)
      at async AuthHandler (/app/node_modules/next-auth/core/index.js:208:28)
      at async NextAuthApiHandler (/app/node_modules/next-auth/next/index.js:22:19)
      at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
      at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
      at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:600:9)
      at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'github',
  message: 'State cookie was missing.'
}

**Comment by rohan-chaturvedi** [comment]
Looks like this is a [known bug in next-auth](https://github.com/nextauthjs/next-auth/discussions/7491) with a variety of causes, but one that we haven't seen before in the Phase Console. I'm looking in to potential fixes.

**Comment by rohan-chaturvedi** [comment]
@FilipSwiatczak To confirm, when you click "Login with Github", you are never redirected to GitHub? It just redirects back to the Phase Console login page?

**Comment by FilipSwiatczak** [comment]
@rohan-chaturvedi no, the github Auth pop up works fine, and the OAuth App counts as having 1 active user
aka: https://github.com/settings/applications/<app-id> shows 1 User

Something goes wrong post auth when communication with backend is attempted, looks to me

**Comment by rohan-chaturvedi** [comment]
@FilipSwiatczak Could you verify that the backend is up and healthy by opening  `https://localhost/service/493c5048-99f9-4eac-ad0d-98c3740b491f/health`  in the browser or curling it?

**Comment by FilipSwiatczak** [comment]
@rohan-chaturvedi yes!
```
{
    "status": "alive"
}
```
No errors in container logs for either Backend or Worker.
I also noticed Nginx container throws a section on boot:
```
2024/06/11 10:07:55 [emerg] 48#48: io_setup() failed (38: Function not implemented)
2024/06/11 10:07:55 [emerg] 53#53: io_setup() failed (38: Function not implemented)
2024/06/11 10:07:55 [emerg] 52#52: io_setup() failed (38: Function not implemented)
2024/06/11 10:07:55 [emerg] 54#54: io_setup() failed (38: Function not implemented)
2024/06/11 10:07:55 [emerg] 50#50: io_setup() failed (38: Function not implemented)
```
might be relevant

**Comment by rohan-chaturvedi** [comment]
> @rohan-chaturvedi yes!
> 
> ```
> {
>     "status": "alive"
> }
> ```
> 
> No errors in container logs for either Backend or Worker. I also noticed Nginx container throws a section on boot:
> 
> ```
> 2024/06/11 10:07:55 [emerg] 48#48: io_setup() failed (38: Function not implemented)
> 2024/06/11 10:07:55 [emerg] 53#53: io_setup() failed (38: Function not implemented)
> 2024/06/11 10:07:55 [emerg] 52#52: io_setup() failed (38: Function not implemented)
> 2024/06/11 10:07:55 [emerg] 54#54: io_setup() failed (38: Function not implemented)
> 2024/06/11 10:07:55 [emerg] 50#50: io_setup() failed (38: Function not implemented)
> ```
> 
> might be relevant

Hmm odd, doesn't look like there's anything wrong with the backend. I can't seem to replicate this issue on a fresh instance either. 

Could you try adding `DEBUG=True` in your .env, restarting the console and trying the login again? It will give us more verbose logs to work with.

**Comment by FilipSwiatczak** [comment]
Frontend container log:
```
✓ Starting...
 ✓ Ready in 3s
[next-auth][warn][DEBUG_ENABLED] 
https://next-auth.js.org/warnings#debug_enabled
[next-auth][debug][CREATE_STATE] { value: 'XXX', maxAge: 900 }
[next-auth][debug][GET_AUTHORIZATION_URL] {
  url: 'https://github.com/login/oauth/authorize?client_id=xxx&scope=read%3Auser%20user%3Aemail&response_type=code&redirect_uri=https%3A%2F%2Flocalhost%2Fapi%2Fauth%2Fcallback%2Fgithub&state=xxx',
  cookies: [
    {
      name: '__Secure-next-auth.state',
      value: 'xxx',
      options: [Object]
    }
  ],
  provider: {
    id: 'github',
    name: 'GitHub',
    type: 'oauth',
    authorization: {
      url: 'https://github.com/login/oauth/authorize',
      params: [Object]
    },
    token: { url: 'https://github.com/login/oauth/access_token', params: {} },
    userinfo: {
      url: 'https://api.github.com/user',
      request: [AsyncFunction: request]
    },
    profile: [Function: profile],
    style: { logo: '/github.svg', bg: '#24292f', text: '#fff' },
    idToken: false,
    checks: [ 'state' ],
    clientId: 'xxx',
    clientSecret: 'xxx',
    signinUrl: 'https://localhost/api/auth/signin/github',
    callbackUrl: 'https://localhost/api/auth/callback/github'
  }
}
[next-auth][debug][PROFILE_DATA] {
  OAuthProfile: {
    login: 'FilipSwiatczak',
    id: 30108240,
    (...)
    two_factor_authentication: true,
  }
}
[next-auth][debug][OAUTH_CALLBACK_RESPONSE] {
  profile: {
    name: 'Filip Swiatczak',
    image: 'https://avatars.githubusercontent.com/u/30108240?v=4'
  },
  account: {
    provider: 'github',
    type: 'oauth',
    providerAccountId: 'xxx',
    access_token: 'xxx',
    token_type: 'bearer',
    scope: 'read:user,user:email'
  },
  OAuthProfile: {
    login: 'FilipSwiatczak',
    (...)
    two_factor_authentication: true,
  }
}
AxiosError: connect ECONNREFUSED 127.0.0.1:443
    at AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:610:25)
    at RedirectableRequest.emit (node:events:518:28)
    at eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (file:///app/node_modules/axios/lib/core/Axios.js:45:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.jwt (/app/.next/server/pages/api/auth/[...nextauth].js:1:2745)
    at async Object.callback (/app/node_modules/next-auth/core/routes/callback.js:135:25)
    at async AuthHandler (/app/node_modules/next-auth/core/index.js:208:28)
    at async NextAuthApiHandler (/app/node_modules/next-auth/next/index.js:22:19)
    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:600:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37) {
  port: 443,
  address: '127.0.0.1',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -111,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0',
      'X-forwarded-for': '172.19.0.1',
      'Content-Length': '59',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    withCredentials: true,
    method: 'post',
    url: 'https://localhost/service/social/login/github/',
    data: '{"access_token":"xxx"}'
  },
  request: <ref *1> Writable {
    _events: {
      close: undefined,
      error: [Function: handleRequestError],
      prefinish: undefined,
      finish: undefined,
      drain: undefined,
      response: [Function: handleResponse],
      socket: [Function: handleRequestSocket]
    },
    _writableState: WritableState {
      highWaterMark: 16384,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 17580812,
      [Symbol(kBufferedValue)]: null
    },
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/service/social/login/github/',
      method: 'POST',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'localhost',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/service/social/login/github/'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 59,
    _requestBodyBuffers: [ [Object] ],
    _eventsCount: 3,
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '59',
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /service/social/login/github/ HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0\r\n' +
        'X-forwarded-for: 172.19.0.1\r\n' +
        'Content-Length: 59\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: localhost\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/service/social/login/github/',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://localhost/service/social/login/github/',
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ECONNREFUSED 127.0.0.1:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 443
  }
}
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error undefined Backend error

**Comment by FilipSwiatczak** [comment]
@rohan-chaturvedi before we delve too deep here I should add I'm running Mac M1 and Rosetta and I had to add:
`platform: linux/x86_64`
to all services in the docker-compose
which ended up building the phase-nginx on local. 

I suspect it might be the culprit here somehow if it works out of the box for you

**Comment by rohan-chaturvedi** [comment]
> @rohan-chaturvedi before we delve too deep here I should add I'm running Mac M1 and Rosetta and I had to add: `platform: linux/x86_64` to all services in the docker-compose which ended up building the phase-nginx on local.
> 
> I suspect it might be the culprit here somehow if it works out of the box for you

Oh, interesting. Let me check if this might cause an issue. I'll try and get a hold of an M1 Mac to test things as well and get back to you!

**Comment by rohan-chaturvedi** [comment]
@FilipSwiatczak Could you Updating the `BACKEND_API_BASE` to `http://backend:8000` for the `frontend` container?

```
frontend:
    container_name: phase-frontend
    restart: unless-stopped
    depends_on:
      - backend
    image: phasehq/frontend:latest
    env_file: .env
    environment:
      NEXTAUTH_URL: "${HTTP_PROTOCOL}${HOST}"
      BACKEND_API_BASE: "http://backend:8000" # update this
      NEXT_PUBLIC_BACKEND_API_BASE: "${HTTP_PROTOCOL}${HOST}/service"
      NEXT_PUBLIC_NEXTAUTH_PROVIDERS: "${SSO_PROVIDERS}"
    networks:
      - phase-net
```

**Comment by FilipSwiatczak** [comment]
@rohan-chaturvedi Bingo! That fixed it! Guess the backend was not discoverable under 127.0.0.1 and the docker service reference did it! Thanks Rohan that was quick :)

**Comment by rohan-chaturvedi** [comment]
> @rohan-chaturvedi Bingo! That fixed it! Guess the backend was not discoverable under 127.0.0.1 and the docker service reference did it! Thanks Rohan that was quick :)

Great! Yeah, this was our mistake, I will update the `docker-compose.yml` with this change. Sorry for the trouble!
